### PR TITLE
Fix wall

### PR DESCRIPTION
**Pull request by michaelnguyen974**
Fixed the con wall

### CODE REVIEW

**Review by hotblack86 — APPROVED** [review]
Good refactor. Game is taking shape nicely.

**Review by matharotheelf — APPROVED** [review]
Nice to have walls.

**Review by matharotheelf — APPROVED** [review]
Nice to have walls. Let's collide with them

**Review by CKKH — APPROVED** [review]
🔥

**Comment by CKKH** [comment]
Wall bug fixed

**Pull request merged**
